import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.library'
    id 'maven-publish'
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = 'com.welie.blessed'
    compileSdk = 36

    defaultConfig {
        minSdk = 26

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
        targetSdk 36
    }
    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
    lint {
        targetSdk 36
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

dependencies {
    implementation libs.timber
    testImplementation libs.junit
    testImplementation libs.mockk
    testImplementation libs.robolectric
}

afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.weliem'
                artifactId = 'blessed-kotlin'
                version = '3.1.0.1-baracoda'
            }
        }
    }
}